CarPool/CarPool.Web/Controllers/InboxController.cs
using CarPool.Common;
using CarPool.Services.Data.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CarPool.Web.Controllers
{
    [Authorize(Roles = GlobalConstants.UserRoleName + "," + GlobalConstants.AdministratorRoleName)]
    public class InboxController : Controller
    {
        private readonly IInboxService _inbox;

        public InboxController(IInboxService inbox)
        {
            _inbox = inbox;
        }

        public async Task<IActionResult> Index()
        {
            var userEmail = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email).Value;

            var model = await _inbox.GetUserMessages(userEmail);
            return View(model);
        }
    }
}

CarPool/CarPool.Web/Controllers/TripController.cs
using CarPool.Common;
using CarPool.Services.Data.Contracts;
using CarPool.Services.Mapping.DTOs;
using CarPool.Web.Infrastructure.Extensions;
using CarPool.Web.ViewModels.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CarPool.Web.Controllers
{
    [Authorize(Roles = GlobalConstants.UserRoleName + "," + GlobalConstants.AdministratorRoleName)]
    public class TripController : Controller
    {
        private readonly ITripService _trip;
        private readonly IApplicationUserService _user;
        private readonly IRatingService _rating;

        public TripController(ITripService trip, IApplicationUserService user, IRatingService rating)
        {
            _trip = trip;
            _user = user;
            _rating = rating;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var trips = await _trip.GetAllUpcomingTripsAsync(0);
            var maxpages = await _trip.GetPageCountAsync();

            var model = new TripViewModel()
            {
                CurrentPage = 0,
                MaxPages = maxpages,
                UpcomingTrips = trips,
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Index([FromQuery] int p)
        {
            var trips = await _trip.GetAllUpcomingTripsAsync(p);
            var maxpages = await _trip.GetPageCountAsync();

            var model = new TripViewModel()
            {
                CurrentPage = p,
                MaxPages = maxpages,
                UpcomingTrips = trips
            };

            return Json(new { isValid = true, html = await Helper.RenderViewAsync(this, "_TableTrips", model, true) });
        }

        [HttpGet]
        public async Task<IActionResult> MyTrips()
        {
            var userEmail = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email).Value;
            var trips = await _trip.GetUpcomingTripsByUserAsync(0, userEmail);
            var manageableTrips = await _trip.GetUpcomingTripsByUserAsDriverAsync(0, userEmail);
            var pastTrips = await _trip.GetPastByUserTrips(0, userEmail);
            var maxpages = await _trip.GetPageCountPerUserAsync(userEmail);

            var model = new TripViewModel()
            {
                UpcomingTrips = trips,
                PastTrips = pastTrips,
                CurrentPage = 0,
                MaxPages = maxpages,
                ManageableTrips = manageableTrips
            };
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> MyTrips([FromQuery] int p)
        {
            var userEmail = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email).Value;
            var trips = await _trip.GetUpcomingTripsByUserAsync(p, userEmail);
            var manageableTrips = await _trip.GetUpcomingTripsByUserAsDriverAsync(0, userEmail);
            var pasttrips = await _trip.GetPastByUserTrips(p, userEmail);
            var maxpages = await _trip.GetPageCountPerUserAsync(userEmail);

            var model = new TripViewModel()
            {
                UpcomingTrips = trips,
                PastTrips = pasttrips,
                MaxPages = maxpages,
                CurrentPage = p,
                ManageableTrips = manageableTrips
            };

            return Json(new { isValid = true, html = await Helper.RenderViewAsync(this, "_TableMyTrips", model, true) });
        }

        public async Task<IActionResult> Create()
        {
            var requestEmail = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email).Value;
            var driver = await _user.GetUserByEmailOrIdAsync(requestEmail);

            if (driver.HasVehicle)
            {
                return RedirectToAction("Index", "Vehicle");
            }

            return View(new TripViewModel() { Date = DateTime.Today });
        }

        [HttpPost]
        public async Task<IActionResult> Create(TripViewModel obj)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { isValid = false, html = await Helper.RenderViewAsync(this, "Create", obj, false) });
            }

            var requestEmail = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email).Value;
            var driver = await _user.GetUserByEmailOrIdAsync(requestEmail);

            await _trip.PostAsync(new TripDTO()
            {
                AdditionalComment = obj.AdditionalComment,
                DepartureTime = obj.Date,
                DestinationAddressCountry = obj.DestinationCountry,
                DestinationAddressCity = obj.DestinationCity,
                StartAddressCity = obj.OriginCity,
                StartAddressCountry = obj.OriginCountry,
                DriverId = driver.Id.ToString(),
                FreeSeats = obj.FreeSeats
            });

            var trips = new TripViewModel
            {
                UpcomingTrips = await _trip.GetAllUpcomingTripsAsync(0),
                MaxPages = await _trip.GetPageCountAsync(),
                CurrentPage = 0
            };

            return Json(new { isValid = true, html = await Helper.RenderViewAsync(this, "_TableTrips", trips, true) });
        }

        [HttpPost]
        public async Task<IActionResult> Join(int id)
        {
            var userEmail = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email).Value;

            await _trip.JoinTripAsync(id, userEmail);

            return await Index(0);
        }

        [HttpPost]
        public async Task<IActionResult> Leave(int id)
        {
            var userEmail = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email).Value;

            await _trip.LeaveTripAsync(id, userEmail);

            return await MyTrips(0);

        }

        [HttpGet]
        public async Task<IActionResult> Rating()
        {
            return View(new RatingViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Rating(RatingViewModel obj, int id)
        {
            var userEmail = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email).Value;
            var feedbackFromUser = await _user.GetUserByEmailOrIdAsync(userEmail);
            var trip = await _trip.GetTripByIDAsync(id);

            var response = await _rating.PostFeedbackAsync(
                new RatingDTO
                {
                    AddedByUserId = feedbackFromUser.Id,
                    ApplicationUserId = Guid.Parse(trip.DriverId),
                    Feedback = obj.Comment,
                    TripId = id,
                    Value = obj.Value
                });

            return await MyTrips(0);
        }

        [HttpGet]
        public IActionResult Report()
        {
            return View(new RatingViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Report(RatingViewModel obj, int id)
        {
            var userEmail = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email).Value;
            var feedbackFromUser = await _user.GetUserByEmailOrIdAsync(userEmail);
            var trip = await _trip.GetTripByIDAsync(id);

            var response = await _rating.PostFeedbackAsync(
                new RatingDTO
                {
                    AddedByUserId = feedbackFromUser.Id,
                    ApplicationUserId = Guid.Parse(trip.DriverId),
                    Feedback = obj.Comment,
                    TripId = id,
                    IsReport = true
                });

            return await MyTrips(0);
        }

        [HttpPost]
        public async Task<IActionResult> KickUser(string id, int tripid)
        {
            var userEmail = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email).Value;

            var action = await _trip.KickUserAsync(id, tripid, userEmail);

            return await MyTrips(0);
        }
    }
}

CarPool/CarPool.Web/Views/Shared/_Layout.cshtml
@{
    //var cookie = this.ViewContext.HttpContext.Request.Cookies["auth_cookie"] != null;
    var role = Context.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Role)?.Value;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ride Share</title>

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/images/favicon.png">

    <!-- CSS ============================================ -->
    <link rel="stylesheet" href="~/assets/css/vendor/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/plugins/animation.css">
    <link rel="stylesheet" href="~/assets/css/plugins/feature.css">
    <link rel="stylesheet" href="~/assets/css/plugins/magnify.min.css">
    <link rel="stylesheet" href="~/assets/css/plugins/slick.css">
    <link rel="stylesheet" href="~/assets/css/plugins/slick-theme.css">
    <link rel="stylesheet" href="~/assets/css/plugins/lightbox.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="stylesheet" href="~/assets/css/custom.css">
    @RenderSection("Styles", required: false)

</head>

<body class="active-dark-mode">
    <main class="page-wrapper">
        <div class="header-transparent-with-topbar">
            <!-- Start Header Area  -->
            <header class="rn-header header-default header-transparent header-sticky">
                <div class="container position-relative">
                    <div class="row align-items-center row--0">
                        <div class="col-lg-3 col-md-6 col-4">
                            <div class="logo">
                                <a href="@Url.Action("Index", "Home")">
                                    <img class="logo-light" src="~/assets/images/logo/logo.png" alt="Corporate Logo">
                                    <img class="logo-dark" src="~/assets/images/logo/logo-dark.png" alt="Corporate Logo">
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-9 col-md-6 col-8 position-static">
                            <div class="header-right">
                                @if (role == null || role != null && role == GlobalConstants.NotConfirmedRoleName)
                                {
                                <nav class="mainmenu-nav d-none d-lg-block">
                                    <ul class="mainmenu">
                                        <li class="has-droupdown has-menu-child-item">
                                            <a asp-controller="Home" asp-action="Index">Home</a>
                                        </li>
                                        <li><a asp-controller="Home" asp-action="About">About</a></li>

                                        <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                                    </ul>


                                </nav>
                                }
                                <!-- Start Header Btn  -->
                                @if (role != null && role != GlobalConstants.NotConfirmedRoleName)
                                {
                                    if (role == GlobalConstants.UserRoleName)
                                    {
                                <div class="btn"><a class="btn-default text-underline btn-small" asp-controller="Trip" asp-action="Index">Trips</a></div>
                                    }
                                    else if (role == GlobalConstants.AdministratorRoleName)
                                    {
                                <div class="btn">
                                    <a asp-action="index" asp-controller="Ban"
                                       class="btn-default text-underline btn-small">Ban</a>
                                </div>
                                    }

                                <div class="btn"><a class="far fa-envelope fa-3x" asp-controller="Inbox" asp-action="Index"></a></div>
                                <div class="btn"><a class="fas fa-cog fa-3x settings-btn" style="" asp-controller="Auth" asp-action="Settings"></a></div>
                                <div class="btn"><a class="fas fa-sign-out-alt fa-3x" asp-controller="Auth" asp-action="Logout"></a></div>
                                }
                                else
                                {
                                <div class="btn"><a class="btn-default text-underline btn-small" asp-controller="Auth" asp-action="Login">JOIN US</a></div>
                                }
                                <!-- End Header Btn  -->
                                <!-- Start Mobile-Menu-Bar -->
                                <div class="mobile-menu-bar ml--5 d-block d-lg-none">
                                    <div class="hamberger">
                                        <button class="hamberger-button">
                                            <i class="feather-menu"></i>
                                        </button>
                                    </div>
                                </div>
                                <!-- Start Mobile-Menu-Bar -->


                                <div id="my_switcher" class="my_switcher">
                                    <ul>
                                        <li>
                                            <a href="javascript: void(0);" data-theme="light" class="setColor light">
                                                <img class="sun-image" src="~/assets/images/icons/sun-01.svg" alt="Sun images">
                                            </a>
                                        </li>
                                        <li>
                                            <a href="javascript: void(0);" data-theme="dark" class="setColor dark">
                                                <img class="Victor Image" src="~/assets/images/icons/vector.svg" alt="Vector Images">
                                            </a>
                                        </li>
                                    </ul>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- End Header Area  -->
            <!-- ***** Preloader Start ***** -->
            <div id="preloader">
                <div class="jumper">
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            </div>
            <!-- ***** Preloader End ***** -->
            <!--Modal Start-->
            <div class="modal" id="form-modal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title"></h5>
                        </div>
                        <div class="modal-body">

                        </div>
                    </div>
                </div>
            </div>
            <!--Modal End-->
            <div class="popup-mobile-menu">
                <div class="inner">
                    <div class="header-top">
                        <div class="logo">
                            <a href="index.html">
                                <img class="logo-light" src="~/assets/images/logo/logo.png" alt="Corporate Logo">
                                <img class="logo-dark" src="~/assets/images/logo/logo-dark.png" alt="Corporate Logo">
                            </a>
                        </div>
                        <div class="close-menu">
                            <button class="close-button">
                                <i class="feather-x"></i>
                            </button>
                        </div>
                    </div>
                    <ul class="mainmenu">
                        <li>
                            <a asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li><a asp-controller="Home" asp-action="About">About</a></li>

                        <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                    </ul>

                </div>
            </div>
        </div>


        <!-- Start Theme Style  -->
        <div>
            <div class="rn-gradient-circle"></div>
            <div class="rn-gradient-circle theme-pink"></div>
        </div>
        <!-- End Theme Style  -->
        <!-- Messenger Chat plugin Code -->
        <div id="fb-root"></div>

        <!-- Your Chat plugin code -->
        <div id="fb-customer-chat" class="fb-customerchat">
        </div>

        <script>
            var chatbox = document.getElementById('fb-customer-chat');
            chatbox.setAttribute("page_id", "106912251841897");
            chatbox.setAttribute("attribution", "biz_inbox");
        </script>

        <!-- Your SDK code -->
        <script>
            window.fbAsyncInit = function () {
                FB.init({
                    xfbml: true,
                    version: 'v12.0'
                });
            };

            (function (d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = 'https://connect.facebook.net/en_US/sdk/xfbml.customerchat.js';
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
        </script>

        @RenderBody()
        <!-- Start Footer Area  -->
        <div class="rwt-brand-area rn-section-gap">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 mt--10">
                        <ul class="brand-list brand-style-2 variation-2">
                            <li><a href="#"><img src="~/assets/images/brand/brand-10.png" alt="Brand Image"></a></li>
                            <li><a href="https://drive.google.com/file/d/1VsYYvLCSnAQjyMbeslrjkq9RUmD4Z7Dg/view?usp=sharing"><img src="~/assets/images/brand/google-play.png" alt="Brand Image"></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Brand Style-4  -->
        <!-- End Footer Area  -->

    </main>

    <!-- All Scripts  -->
    <!-- Start Top To Bottom Area  -->
    <div class="rn-back-top">
        <i class="feather-arrow-up"></i>
    </div>
    <!-- End Top To Bottom Area  -->
    <!-- JS
    ============================================ -->
    <script src="~/assets/js/vendor/modernizr.min.js"></script>
    <script src="~/assets/js/vendor/jquery.min.js"></script>
    <script src="~/assets/js/vendor/bootstrap.min.js"></script>
    <script src="~/assets/js/vendor/popper.min.js"></script>
    <script src="~/assets/js/vendor/waypoint.min.js"></script>
    <script src="~/assets/js/vendor/wow.min.js"></script>
    <script src="~/assets/js/vendor/counterup.min.js"></script>
    <script src="~/assets/js/vendor/feather.min.js"></script>
    <script src="~/assets/js/vendor/sal.min.js"></script>
    <script src="~/assets/js/vendor/masonry.js"></script>
    <script src="~/assets/js/vendor/imageloaded.js"></script>
    <script src="~/assets/js/vendor/magnify.min.js"></script>
    <script src="~/assets/js/vendor/lightbox.js"></script>
    <script src="~/assets/js/vendor/slick.min.js"></script>
    <script src="~/assets/js/vendor/easypie.js"></script>
    <script src="~/assets/js/vendor/text-type.js"></script>
    <script src="~/assets/js/vendor/jquery.style.swicher.js"></script>
    <script src="~/assets/js/vendor/js.cookie.js"></script>
    <script src="https://kit.fontawesome.com/66748f666c.js" crossorigin="anonymous"></script>
    <script src="~/lib/microsoft/signalr/dist/browser/signalr.min.js"></script>
    <!-- Main JS -->
    <script src="~/assets/js/main.js"></script>
    <script src="~/assets/js/custom.js" type="text/javascript"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

CarPool/CarPool.Web/Views/Shared/_LayoutEmpty.cshtml
@{
    var cookie = this.ViewContext.HttpContext.Request.Cookies["auth_cookie"] != null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Drive Share</title>

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/images/favicon.png">

    <!-- CSS ============================================ -->
    <link rel="stylesheet" href="~/assets/css/vendor/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/plugins/animation.css">
    <link rel="stylesheet" href="~/assets/css/plugins/feature.css">
    <link rel="stylesheet" href="~/assets/css/plugins/magnify.min.css">
    <link rel="stylesheet" href="~/assets/css/plugins/slick.css">
    <link rel="stylesheet" href="~/assets/css/plugins/slick-theme.css">
    <link rel="stylesheet" href="~/assets/css/plugins/lightbox.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="stylesheet" href="~/assets/css/custom.css">
    @RenderSection("Styles", required: false)

</head>

<body class="active-dark-mode">
    @RenderBody()

    <!-- End Top To Bottom Area  -->
    <!-- JS
    ============================================ -->
    <script src="~/assets/js/vendor/modernizr.min.js"></script>
    <script src="~/assets/js/vendor/jquery.min.js"></script>
    <script src="~/assets/js/vendor/bootstrap.min.js"></script>
    <script src="~/assets/js/vendor/popper.min.js"></script>
    <script src="~/assets/js/vendor/waypoint.min.js"></script>
    <script src="~/assets/js/vendor/wow.min.js"></script>
    <script src="~/assets/js/vendor/counterup.min.js"></script>
    <script src="~/assets/js/vendor/feather.min.js"></script>
    <script src="~/assets/js/vendor/sal.min.js"></script>
    <script src="~/assets/js/vendor/masonry.js"></script>
    <script src="~/assets/js/vendor/imageloaded.js"></script>
    <script src="~/assets/js/vendor/magnify.min.js"></script>
    <script src="~/assets/js/vendor/lightbox.js"></script>
    <script src="~/assets/js/vendor/slick.min.js"></script>
    <script src="~/assets/js/vendor/easypie.js"></script>
    <script src="~/assets/js/vendor/text-type.js"></script>
    <script src="~/assets/js/vendor/jquery.style.swicher.js"></script>
    <script src="~/assets/js/vendor/js.cookie.js"></script>
    <!-- Main JS -->
    <script src="~/assets/js/main.js"></script>
    <script src="~/assets/js/custom.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>